import * as fs from 'fs';
import * as path from 'path';
const outputFile = './src/dsRootFS.ts';
const webFileDir = './src/root';
const binFileDir = './src/process';

let header = `/*
 * !!! AUTOGENERATED FILE !!!
 *
 * Do not edit manually!
 * Run 'yarn genrootfs' to regenerate
 * 
 */
import { DSFilePerms, DSFileSystem, DSRAMFileSystem, DSIDirectory, DSInode } from "./dsFileSystem";
import { DSIProcessFile } from "./filesystem/dsIProcessFile";
import { DSIWebFile } from "./filesystem/dsIWebFile";

`;

const buildrootfs_header = `
// BUILDROOTFS HEADER
export function buildrootfs(): DSFileSystem {
    const fs = new DSRAMFileSystem();
`;

const main_footer =
    `
    // BUILDROOTFS FOOTER
    fs.root.chmod(DSFilePerms.rx());
    fs.readonly = true;

    return fs;
}
`;

function sanitize(input: string): string {
    // Replace all characters not valid for variable names (letters, digits, or underscores)
    const sanitized = input.replace(/[^a-zA-Z0-9_]/g, '_');

    // If the first character is a digit, prepend an underscore
    return sanitized.replace(/^[0-9]/, '_');
}

let webfile_traversal_imports = '// WEBFILE TRAVERSAL IMPORTS\n';
const webfile_traversal_header = `
    // WEBFILE TRAVERSAL HEADER
    let dirstack: DSIDirectory[] = [];
    let curdir = fs.root;
    let curfile: DSIWebFile;

`;

let webfile_traversal_body = '    // WEBFILE TRAVERSAL BODY\n';

function webfileTraverseAndGenerate(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(dir, entry.name);
        const relPath = srcPath.replace(/^src\//, '');

        // Create directory
        if (entry.isDirectory()) {
            console.log(`Create Directory ${srcPath}`);
            webfile_traversal_body += `
    // Traversing ${relPath}
    dirstack.push(curdir);
    curdir = curdir.mkdir('${entry.name}');
    `;
            webfileTraverseAndGenerate(srcPath);
            webfile_traversal_body += `
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited ${relPath}
        `;
        }

        // Create File
        else if (entry.isFile()) {
            console.log(`Create file from ${srcPath}`);
            const stats = fs.lstatSync(srcPath);
            const execperms = stats.mode & 0o111;
            const permstring = execperms ? `curfile.chmod(DSFilePerms.rx());` : "";
            let varname = sanitize(relPath);
            webfile_traversal_imports += `import ${varname} from "./${relPath}";\n`
            webfile_traversal_body += `
    // Creating ${relPath}
    curfile = new DSIWebFile(fs, ${varname});
    curdir.addfile("${entry.name}", curfile);
    ${permstring}
    `;
        } else {
            console.log(`skipping ${srcPath}`);
        }
    }
}

console.log(`Doing bin file generation from ${binFileDir}`);

let bin_imports = '// BIN IMPORTS\n';
const bin_header = `
    // BIN HEADER
    const bindir = fs.root.mkdir('bin');
    let binfile: DSInode;

`;
let bin_body = '    // BIN BODY\n';
const entries = fs.readdirSync(binFileDir, { withFileTypes: true });
for (const entry of entries) {
    const srcPath = path.join(entry.parentPath, entry.name);
    const importPath = srcPath.replace(/^src\//, '').replace(/.ts$/, '');
    let match = importPath.match(/([^\/]+)$/);
    if (!match)
        throw Error("could not extract bin filename");
    const binFileName = match[1];

    console.log(`Create ${binFileName} from ${srcPath}`);
    const file = fs.readFileSync(srcPath, 'utf-8');
    match = file.match(/export class (\w+) extends (DSProcess|DSApp) {/);
    if (!match)
        throw Error("could not find DSProcess class");
    const className = match[1];
    bin_imports += `import { ${className} } from "./${importPath}";\n`
    bin_body += `
    binfile = new DSIProcessFile(fs, ${className});
    bindir.addfile("${binFileName}", binfile);
    `;

}
const bin_footer = `
    // BIN FOOTER
    bindir.chmod(DSFilePerms.rx());
`;

console.log(`Doing web file traversal in ${webFileDir}`);
webfileTraverseAndGenerate(webFileDir);

console.log(`Writing ${outputFile}`);
fs.writeFileSync(outputFile,
    header
    + bin_imports
    + webfile_traversal_imports
    + buildrootfs_header
    + bin_header
    + bin_body
    + bin_footer
    + webfile_traversal_header
    + webfile_traversal_body
    + main_footer
);