import * as fs from 'fs';
import * as path from 'path';

const outputFile = './src/dsRootFS.ts';
const webFileDir = './src/rootfs';

let header = `/*
 * !!! AUTOGENERATED FILE !!!
 *
 * Do not edit manually!
 * Run 'yarn genrootfs' to regenerate
 * 
 */
import { DSFilePerms, DSFileSystem, DSIDirectory, DSInode } from "./dsFileSystem";
import { DSIProcessFile } from "./filesystem/dsIProcessFile";
import { DSIWebFile } from "./filesystem/dsIWebFile";
import { DSRAMFileSystem } from "./filesystem/dsRAMFileSystem";

`;

const buildrootfs_header = `
// BUILDROOTFS HEADER
export function buildrootfs(): DSFileSystem {
    const fs = new DSRAMFileSystem();
`;

const main_footer =
    `
    // BUILDROOTFS FOOTER
    fs.root.chmod(DSFilePerms.rx());
    fs.readonly = true;

    return fs;
}
`;

function sanitize(input: string): string {
    // Replace all characters not valid for variable names (letters, digits, or underscores)
    const sanitized = input.replace(/[^a-zA-Z0-9_]/g, '_');

    // If the first character is a digit, prepend an underscore
    return sanitized.replace(/^[0-9]/, '_');
}

const webfile_traversal_header = `
    // WEBFILE TRAVERSAL HEADER
    let dirstack: DSIDirectory[] = [];
    let curdir = fs.root;
    let curfile: DSIWebFile;
    let binfile: DSInode;

`;

type DirectoryNode = {
    type: 'dir';
    name: string;
    relPath: string;
    children: Map<string, DirectoryNode | FileNode>;
};

type FileNode = {
    type: 'file';
    name: string;
    relPath: string; // path in the final filesystem (layer-stripped)
    importPath: string; // path used in TS import (keeps layer prefix)
    className?: string;
    sanitized: string;
    executable: boolean;
};

function toPosix(inputPath: string): string {
    return inputPath.split(path.sep).join('/');
}

function processFilename(srcPath: string): string | null {
    const file = fs.readFileSync(srcPath, 'utf-8');
    const match = file.match(/export class (\w+) extends (DSProcess|DSApp|DSArcadeGame) {/);
    return match ? match[1] : null;
}

function createRootNode(): DirectoryNode {
    return { type: 'dir', name: '', relPath: '', children: new Map() };
}

function ensureDir(root: DirectoryNode, dirParts: string[]): DirectoryNode {
    let current = root;
    let currentRel = '';

    for (const part of dirParts) {
        const nextRel = currentRel ? `${currentRel}/${part}` : part;
        const existing = current.children.get(part);
        if (existing && existing.type === 'dir') {
            current = existing;
            currentRel = nextRel;
            continue;
        }

        const newDir: DirectoryNode = {
            type: 'dir',
            name: part,
            relPath: nextRel,
            children: new Map(),
        };
        current.children.set(part, newDir);
        current = newDir;
        currentRel = nextRel;
    }

    return current;
}

function addFile(root: DirectoryNode, file: FileNode) {
    const parts = file.relPath.split('/').filter(Boolean);
    const dirParts = parts.slice(0, -1);
    const parent = ensureDir(root, dirParts);
    // Later layers override earlier ones when the exact path matches
    parent.children.set(file.name, file);
}

function walkLayer(layerName: string, root: DirectoryNode) {
    const layerAbs = path.join(webFileDir, layerName);

    function walk(absDir: string, relTarget: string) {
        const entries = fs.readdirSync(absDir, { withFileTypes: true });
        for (const entry of entries) {
            const entryAbs = path.join(absDir, entry.name);
            const targetRel = toPosix(path.join(relTarget, entry.name));

            if (entry.isDirectory()) {
                walk(entryAbs, targetRel);
            } else if (entry.isFile()) {
                const stats = fs.lstatSync(entryAbs);
                const executable = Boolean(stats.mode & 0o111);
                const isTypeScript = path.extname(entryAbs) === '.ts';
                const className = isTypeScript ? processFilename(entryAbs) : null;
                const importPath = toPosix(path.join('rootfs', layerName, relTarget, entry.name));
                const fileNode: FileNode = {
                    type: 'file',
                    name: entry.name,
                    relPath: targetRel,
                    importPath: className ? importPath.replace(/\.ts$/, '') : importPath,
                    className: className || undefined,
                    sanitized: sanitize(importPath),
                    executable,
                };
                addFile(root, fileNode);
            } else {
                console.log(`skipping ${entryAbs}`);
            }
        }
    }

    walk(layerAbs, '');
}

function collectImports(node: DirectoryNode): string[] {
    const imports: string[] = [];
    for (const child of Array.from(node.children.values())) {
        if (child.type === 'dir') {
            imports.push(...collectImports(child));
        } else if (child.className) {
            imports.push(`import { ${child.className} } from "./${child.importPath}";`);
        } else {
            imports.push(`import ${child.sanitized} from "./${child.importPath}";`);
        }
    }
    return imports;
}

function generateFileBody(file: FileNode): string {
    if (file.className) {
        const binFileName = path.posix.basename(file.importPath);
        return `
    binfile = new DSIProcessFile(fs, ${file.className});
    curdir.addfile("${binFileName}", binfile);
     `;
    }

    const permLine = file.executable ? `
    curfile.chmod(DSFilePerms.rx());` : '';
    return `
    // Creating ${file.relPath}
    curfile = fs.createInode(${file.sanitized}) as DSIWebFile;
    curdir.addfile("${file.name}", curfile);${permLine}
    `;
}

function generateTraversal(node: DirectoryNode, includeHeader = false): string {
    let body = includeHeader ? '    // WEBFILE TRAVERSAL BODY\n' : '';

    const directories: DirectoryNode[] = [];
    const files: FileNode[] = [];
    for (const child of Array.from(node.children.values())) {
        if (child.type === 'dir') {
            directories.push(child);
        } else {
            files.push(child);
        }
    }

    for (const child of directories) {
        const displayPath = child.relPath || child.name || '/';
        body += `
    // Traversing ${displayPath}
    dirstack.push(curdir);
    curdir = curdir.mkdir('${child.name}');
    `;
        body += generateTraversal(child);
        body += `
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited ${displayPath}
        `;
    }

    for (const child of files) {
        body += generateFileBody(child);
    }

    return body;
}

console.log(`Building layered rootfs from ${webFileDir}`);
const root = createRootNode();
const layers = fs.readdirSync(webFileDir, { withFileTypes: true }).filter(e => e.isDirectory());
for (const layer of layers) {
    console.log(`  scanning ${layer.name}...`)
    walkLayer(layer.name, root);
}

const importBlock = ['// WEBFILE TRAVERSAL IMPORTS', ...collectImports(root)].join('\n') + '\n';
const traversalBody = generateTraversal(root, true);

console.log(`Writing ${outputFile}`);
fs.writeFileSync(
    outputFile,
    header + importBlock + buildrootfs_header + webfile_traversal_header + traversalBody + main_footer
);
