/*
 * !!! AUTOGENERATED FILE !!!
 *
 * Do not edit manually!
 * Run 'yarn genrootfs' to regenerate
 * 
 */
import { DSFilePerms, DSFileSystem, DSRAMFileSystem, DSIDirectory, DSInode } from "./dsFileSystem";
import { DSIProcessFile } from "./filesystem/dsIProcessFile";
import { DSIStaticWebFile } from "./filesystem/dsIStaticWebFile";

// BIN IMPORTS
import { PRCat } from "./process/cat";
import { DSShell } from "./process/dssh";
import { PREcho } from "./process/echo";
import { PREnv } from "./process/env";
import { PRFile } from "./process/file";
import { PRInit } from "./process/init";
import { PRLs } from "./process/ls";
import { PRMkdir } from "./process/mkdir";
import { PRPs } from "./process/ps";
import { PRPwd } from "./process/pwd";
import { PRSleep } from "./process/sleep";
// STATIC TRAVERSAL IMPORTS
import root_data_bazisa_txt from "./root/data/bazisa.txt";
import root_data_deprecated_systems_incorporated_txt from "./root/data/deprecated_systems_incorporated.txt";
import root_data_depsys_txt from "./root/data/depsys.txt";
import root_data_gorzocrop_png from "./root/data/gorzocrop.png";
import root_etc_dsos_conf from "./root/etc/dsos.conf";

// BUILDROOTFS HEADER
export function buildrootfs(): DSFileSystem {
    const fs = new DSRAMFileSystem();

    // BIN HEADER
    const bindir = fs.root.mkdir('bin');
    let binfile: DSInode;

    // BIN BODY

    binfile = new DSIProcessFile(fs, PRCat);
    bindir.addfile("cat", binfile);
    
    binfile = new DSIProcessFile(fs, DSShell);
    bindir.addfile("dssh", binfile);
    
    binfile = new DSIProcessFile(fs, PREcho);
    bindir.addfile("echo", binfile);
    
    binfile = new DSIProcessFile(fs, PREnv);
    bindir.addfile("env", binfile);
    
    binfile = new DSIProcessFile(fs, PRFile);
    bindir.addfile("file", binfile);
    
    binfile = new DSIProcessFile(fs, PRInit);
    bindir.addfile("init", binfile);
    
    binfile = new DSIProcessFile(fs, PRLs);
    bindir.addfile("ls", binfile);
    
    binfile = new DSIProcessFile(fs, PRMkdir);
    bindir.addfile("mkdir", binfile);
    
    binfile = new DSIProcessFile(fs, PRPs);
    bindir.addfile("ps", binfile);
    
    binfile = new DSIProcessFile(fs, PRPwd);
    bindir.addfile("pwd", binfile);
    
    binfile = new DSIProcessFile(fs, PRSleep);
    bindir.addfile("sleep", binfile);
    
    // BIN FOOTER
    bindir.chmod(DSFilePerms.rx());

    // STATIC TRAVERSAL HEADER
    let dirstack: DSIDirectory[] = [];
    let curdir = fs.root;
    let curfile: DSIStaticWebFile;

    // STATIC TRAVERSAL BODY

    // Traversing root/data
    dirstack.push(curdir);
    curdir = curdir.mkdir('data');
    
    // Creating root/data/bazisa.txt
    curfile = new DSIStaticWebFile(fs, root_data_bazisa_txt);
    curdir.addfile("bazisa.txt", curfile);
        
    // Creating root/data/deprecated_systems_incorporated.txt
    curfile = new DSIStaticWebFile(fs, root_data_deprecated_systems_incorporated_txt);
    curdir.addfile("deprecated_systems_incorporated.txt", curfile);
        
    // Creating root/data/depsys.txt
    curfile = new DSIStaticWebFile(fs, root_data_depsys_txt);
    curdir.addfile("depsys.txt", curfile);
        
    // Creating root/data/gorzocrop.png
    curfile = new DSIStaticWebFile(fs, root_data_gorzocrop_png);
    curdir.addfile("gorzocrop.png", curfile);
        
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/data
        
    // Traversing root/etc
    dirstack.push(curdir);
    curdir = curdir.mkdir('etc');
    
    // Creating root/etc/dsos.conf
    curfile = new DSIStaticWebFile(fs, root_etc_dsos_conf);
    curdir.addfile("dsos.conf", curfile);
        
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/etc
        
    // BUILDROOTFS FOOTER
    fs.root.chmod(DSFilePerms.rx());
    fs.readonly = true;

    return fs;
}
