/*
 * !!! AUTOGENERATED FILE !!!
 *
 * Do not edit manually!
 * Run 'yarn genrootfs' to regenerate
 * 
 */
import { DSFilePerms, DSFileSystem, DSRAMFileSystem, DSIDirectory, DSInode } from "./dsFileSystem";
import { DSIProcessFile } from "./filesystem/dsIProcessFile";
import { DSIWebFile } from "./filesystem/dsIWebFile";

// BIN IMPORTS
import { PRCat } from "./process/cat";
import { DSShell } from "./process/dssh";
import { PREcho } from "./process/echo";
import { PREnv } from "./process/env";
import { PRFile } from "./process/file";
import { PRInit } from "./process/init";
import { PRLs } from "./process/ls";
import { PRMDBrowser } from "./process/mdbrowser";
import { PRMkdir } from "./process/mkdir";
import { PRPs } from "./process/ps";
import { PRPwd } from "./process/pwd";
import { PRReset } from "./process/reset";
import { PRSleep } from "./process/sleep";
import { PRTestAnim } from "./process/testanim";
import { PRTestCurses } from "./process/testcurses";
// WEBFILE TRAVERSAL IMPORTS
import root_data_deprecated_systems_incorporated_txt from "./root/data/deprecated_systems_incorporated.txt";
import root_data_depsys_txt from "./root/data/depsys.txt";
import root_data_test_animation_32x32_A_png from "./root/data/test/animation/32x32_A.png";
import root_data_test_animation_32x32_B_png from "./root/data/test/animation/32x32_B.png";
import root_data_test_animation_32x32_C_png from "./root/data/test/animation/32x32_C.png";
import root_data_test_bazisa_txt from "./root/data/test/bazisa.txt";
import root_data_test_image_32x32_test_png from "./root/data/test/image/32x32_test.png";
import root_data_test_image_gorzocrop_png from "./root/data/test/image/gorzocrop.png";
import root_data_test_mdbrowser_test_md from "./root/data/test/mdbrowser.test.md";
import root_etc_autoexec_dssh from "./root/etc/autoexec.dssh";
import root_etc_dsos_conf from "./root/etc/dsos.conf";

// BUILDROOTFS HEADER
export function buildrootfs(): DSFileSystem {
    const fs = new DSRAMFileSystem();

    // BIN HEADER
    const bindir = fs.root.mkdir('bin');
    let binfile: DSInode;

    // BIN BODY

    binfile = new DSIProcessFile(fs, PRCat);
    bindir.addfile("cat", binfile);
    
    binfile = new DSIProcessFile(fs, DSShell);
    bindir.addfile("dssh", binfile);
    
    binfile = new DSIProcessFile(fs, PREcho);
    bindir.addfile("echo", binfile);
    
    binfile = new DSIProcessFile(fs, PREnv);
    bindir.addfile("env", binfile);
    
    binfile = new DSIProcessFile(fs, PRFile);
    bindir.addfile("file", binfile);
    
    binfile = new DSIProcessFile(fs, PRInit);
    bindir.addfile("init", binfile);
    
    binfile = new DSIProcessFile(fs, PRLs);
    bindir.addfile("ls", binfile);
    
    binfile = new DSIProcessFile(fs, PRMDBrowser);
    bindir.addfile("mdbrowser", binfile);
    
    binfile = new DSIProcessFile(fs, PRMkdir);
    bindir.addfile("mkdir", binfile);
    
    binfile = new DSIProcessFile(fs, PRPs);
    bindir.addfile("ps", binfile);
    
    binfile = new DSIProcessFile(fs, PRPwd);
    bindir.addfile("pwd", binfile);
    
    binfile = new DSIProcessFile(fs, PRReset);
    bindir.addfile("reset", binfile);
    
    binfile = new DSIProcessFile(fs, PRSleep);
    bindir.addfile("sleep", binfile);
    
    binfile = new DSIProcessFile(fs, PRTestAnim);
    bindir.addfile("testanim", binfile);
    
    binfile = new DSIProcessFile(fs, PRTestCurses);
    bindir.addfile("testcurses", binfile);
    
    // BIN FOOTER
    bindir.chmod(DSFilePerms.rx());

    // WEBFILE TRAVERSAL HEADER
    let dirstack: DSIDirectory[] = [];
    let curdir = fs.root;
    let curfile: DSIWebFile;

    // WEBFILE TRAVERSAL BODY

    // Traversing root/data
    dirstack.push(curdir);
    curdir = curdir.mkdir('data');
    
    // Creating root/data/deprecated_systems_incorporated.txt
    curfile = new DSIWebFile(fs, root_data_deprecated_systems_incorporated_txt);
    curdir.addfile("deprecated_systems_incorporated.txt", curfile);
    
    
    // Creating root/data/depsys.txt
    curfile = new DSIWebFile(fs, root_data_depsys_txt);
    curdir.addfile("depsys.txt", curfile);
    
    
    // Traversing root/data/test
    dirstack.push(curdir);
    curdir = curdir.mkdir('test');
    
    // Traversing root/data/test/animation
    dirstack.push(curdir);
    curdir = curdir.mkdir('animation');
    
    // Creating root/data/test/animation/32x32_A.png
    curfile = new DSIWebFile(fs, root_data_test_animation_32x32_A_png);
    curdir.addfile("32x32_A.png", curfile);
    
    
    // Creating root/data/test/animation/32x32_B.png
    curfile = new DSIWebFile(fs, root_data_test_animation_32x32_B_png);
    curdir.addfile("32x32_B.png", curfile);
    
    
    // Creating root/data/test/animation/32x32_C.png
    curfile = new DSIWebFile(fs, root_data_test_animation_32x32_C_png);
    curdir.addfile("32x32_C.png", curfile);
    
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/data/test/animation
        
    // Creating root/data/test/bazisa.txt
    curfile = new DSIWebFile(fs, root_data_test_bazisa_txt);
    curdir.addfile("bazisa.txt", curfile);
    
    
    // Traversing root/data/test/image
    dirstack.push(curdir);
    curdir = curdir.mkdir('image');
    
    // Creating root/data/test/image/32x32_test.png
    curfile = new DSIWebFile(fs, root_data_test_image_32x32_test_png);
    curdir.addfile("32x32_test.png", curfile);
    
    
    // Creating root/data/test/image/gorzocrop.png
    curfile = new DSIWebFile(fs, root_data_test_image_gorzocrop_png);
    curdir.addfile("gorzocrop.png", curfile);
    
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/data/test/image
        
    // Creating root/data/test/mdbrowser.test.md
    curfile = new DSIWebFile(fs, root_data_test_mdbrowser_test_md);
    curdir.addfile("mdbrowser.test.md", curfile);
    
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/data/test
        
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/data
        
    // Traversing root/etc
    dirstack.push(curdir);
    curdir = curdir.mkdir('etc');
    
    // Creating root/etc/autoexec.dssh
    curfile = new DSIWebFile(fs, root_etc_autoexec_dssh);
    curdir.addfile("autoexec.dssh", curfile);
    curfile.chmod(DSFilePerms.rx());
    
    // Creating root/etc/dsos.conf
    curfile = new DSIWebFile(fs, root_etc_dsos_conf);
    curdir.addfile("dsos.conf", curfile);
    
    
    curdir.chmod(DSFilePerms.rx());
    curdir = dirstack.pop();
    // Exited root/etc
        
    // BUILDROOTFS FOOTER
    fs.root.chmod(DSFilePerms.rx());
    fs.readonly = true;

    return fs;
}
